osx_image: xcode12.2
language: swift
script: 
 - swift package generate-xcodeproj
 - xcodebuild test -destination 'platform=iOS Simulator,name=iPad (8th generation)' -scheme 'FileBrowserSUI-Package' -disableAutomaticPackageResolution
 
