name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build package
      #run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
      run: swift package generate-xcodeproj
   - name: Run tests
      #run: swift tests --enable-code-coverage -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
      #run: swift tests -v     
        run: xcodebuild test -destination 'platform=iOS name=iPhone 11' -scheme 'FileBrowserSUI-Package' -disableAutomaticPackageResolution -enableCodeCoverage YES
    - name: Test Coverage
      uses: maxep/spm-lcov-action@0.3.1
      with: 
        output-file: ./coverage/lcov.info  
